scripts/make-age-list: Add out_file check
Signed-off-by: Geoff Levand <geoff@infradead.org>

diff --git a/scripts/make-age-list.sh.in b/scripts/make-age-list.sh.in
--- a/scripts/make-age-list.sh.in
+++ b/scripts/make-age-list.sh.in
@@ -120,6 +120,13 @@ fi
 check_top_dir "${top_dir}"
 top_dir="$(realpath -e "${top_dir}")"
 
+out_file="$(realpath -m "${out_file}")"
+
+if [[ -e "${out_file}" && ! -f "${out_file}" ]]; then
+	echo "${script_name}: ERROR: '${out_file}' exists and is not a file." >&2
+	exit 1
+fi
+
 (cd "${top_dir}" && find . -type f -name '*.flac' -exec ls -l --time-style='+%Y.%m.%d' {} \;) \
 	| grep -E --only-matching '[[:digit:]]{4}(\.[[:digit:]]{2}){2} .*$' \
 	| sort > "${out_file}"
